
# To run this application, export SPRING_APPLICATION_JSON, then run spring-boot:run
# export SPRING_APPLICATION_JSON='{"spring": {"datasource": {"url":"jdbc:mysql://[YOUR DB]/aviation", "username":[YOUR USER],"password":[YOUR PW]}}}'
# mvn spring-boot:run

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
        globally_quoted_identifiers: true
    generate-ddl: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

data:
  load: false
  airports_url: https://ourairports.com/data/airports.csv
