spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    repositories:
      enabled: true
    show-sql: false
  datasource:
    url: jdbc:mysql://atlas.byteworksinc.com:3306/aviation
    username: smitchell
    password: $#XewN0ztC
    driver-class-name: com.mysql.cj.jdbc.Driver

data:
  load: true
  airports_url: https://ourairports.com/data/airports.csv
  countries_url: https://ourairports.com/data/countries.csv
  regions_url: https://ourairports.com/data/regions.csv
