spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    repositories:
      enabled: true
    show-sql: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
        globally_quoted_identifiers: true
  datasource:
    url: jdbc:mysql://atlas.byteworksinc.com:3306/aviation
    username: smitchell
    password: $#XewN0ztC
    driver-class-name: com.mysql.cj.jdbc.Driver

data:
  load: true
  airports_url: https://ourairports.com/data/airports.csv
  countries_url: https://ourairports.com/data/countries.csv
  regions_url: https://ourairports.com/data/regions.csv
